# -*- coding: utf-8 -*-
"""MNISY_YSA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mKwXn_oomKJl7Fqqiu3u-_xyotBSWtUZ

## MNST VERİ KÜMESİNİ KULLANARAK YAPAĞ SİNİR AĞLARI İLE RAKAM SINIFLANDIRMA

## MNIST VERİ KÜMESİNİ YÜKLEMEK
"""

from keras.datasets import mnist

(train_images,train_labels),(test_images,test_labels) = mnist.load_data()

train_images.shape

len(train_images)

train_labels

test_images.shape

len(test_images)

test_labels

"""### YAPAY SİNİR AĞI MİMARİSİ"""

from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512,activation='relu',input_shape=(28*28,)))
network.add(layers.Dense(10,activation='softmax'))

"""### YAPAY SİNİR AĞ MODELİNİN DERLENMESİ"""

network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

"""### GİRİŞLERİN VE ETİKETLERİN HAZIRLANMASI"""

train_images = train_images.reshape((60000,28*28))
train_images = train_images.astype('float32')/255

test_images = test_images.reshape((10000,28*28))
test_images = test_images.astype('float32')/255

from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels  = to_categorical(test_labels)

"""## YAPAY SİNİR AĞ MODELİNİN EĞİTİLMESİ"""

network.fit(train_images,train_labels,epochs=5,batch_size=128)

test_loss,test_accuarcy = network.evaluate(test_images,test_labels)

test_loss

test_accuarcy

